### ISSUE TITLE
PUID, getMods

### ISSUE THREAD

**Issue by heathmanms** [nhammond129/ch.py#39]
First Issue:

getMods doesn't exist, this is because it was updated to _getMods
Line 831
    `mods = self.getMods()`
Should be:
    `mods = self._getMods()`

PUID

This used to be in the older ch.py and was removed, it is handy for whois. To fix:
Lines 977 - 989

```
    msg = Message(
      time = mtime,
      user = User(name),
      body = msg,
      raw = rawmsg,
      ip = ip,
      nameColor = nameColor,
      fontColor = fontColor,
      fontFace = fontFace,
      fontSize = fontSize,
      unid = unid,
      room = self
    )
```

Replace with:

```
    msg = Message(
      time = mtime,
      user = User(name),
      body = msg,
      raw = rawmsg,
      ip = ip,
      nameColor = nameColor,
      fontColor = fontColor,
      fontFace = fontFace,
      fontSize = fontSize,
      unid = unid,
      room = self,
      uid = puid
    )
```

Lines 1026 - 1038

```
    msg = Message(
      time = mtime,
      user = User(name),
      body = msg,
      raw = rawmsg,
      ip = ip,
      nameColor = nameColor,
      fontColor = fontColor,
      fontFace = fontFace,
      fontSize = fontSize,
      unid = unid,
      room = self
    )
```

Replace with

```
    msg = Message(
      time = mtime,
      user = User(name),
      body = msg,
      raw = rawmsg,
      ip = ip,
      nameColor = nameColor,
      fontColor = fontColor,
      fontFace = fontFace,
      fontSize = fontSize,
      unid = unid,
      room = self,
      uid = puid
    )
```

Add 
  `def _getUid(self): return self._uid`

Under 
  `def _getUnid(self): return self._unid`

Add
  `uid = property(_getUid)`

Under
  `unid = property(_getUnid)`

---

This has been tested and is working. I make this change everytime you guys update ch.py on my own copy.

**Comment by asl97** [comment]
@heathmanms  updated to your way.

https://github.com/Nullspeaker/ch.py/commit/aa73521774b299603eda7bb99928d718896e3e53

____
note: this is me cleaning up my crappy code on the current main ch.py repo that i know of, i don't have much intention to add feature or fix other horrible parts of the ch.py on this repo
