### ISSUE TITLE
[WIN] Line 2118 - OSError: [WinError 10022] An invalid argument was supplied

### ISSUE THREAD

**Issue by james-d-elliott** [nhammond129/ch.py#54]
Notes: Been running ch.py while playing around with python to create a bot on Linux. Everything works well. Friend wanted to run a bot, so I set up a version for them to play with. Had errors on line 2118, tried with a fresh 3.4.1 install and had the same issues on windows, tried 2.7.8 same deal. Tried example.py, same issues again.

Python Versions Tried: 2.7.8, 3.4.1 (both fresh)
Source: example.py, ch.py latest

Traceback:

```
Room names separated by semicolons: exampleroom
User name: exampleuser
User password: examplepass
Traceback (most recent call last):
  File "example.py", line 33, in <module>
    TestBot.easy_start()
  File "ch.py", line 2159, in easy_start
    self.main()
  File "ch.py", line 2118, in main
    rd, wr, sp = select.select(socks, wsocks, [], self._TimerResolution)
OSError: [WinError 10022] An invalid argument was supplied
```

**Comment by asl97** [comment]
one of the socket is probably just close.

[the disconnect in the room doesn't `None` the _sock variable](https://github.com/Nullspeaker/ch.py/blob/master/ch.py#L772)
[the getConnections doesn't filter closed sockets](https://github.com/Nullspeaker/ch.py/blob/master/ch.py#L2123)

**Comment by asl97** [comment]
Figure out the problem and successfully reproduce it on windows xp (the only computer i have on hand)
it's because three of the args passed to select is a blank list.

this post and the code to reproduce will be edited into the last post in while.
