### ISSUE TITLE
ConnectionRefusedError on 746 not handled.

### ISSUE THREAD

**Issue by james-d-elliott** [nhammond129/ch.py#56]
Hi again,

Just making sure this is an issue before I try and fix it. Currently when connecting to room on a server that's being restarted or updated etc (because often you get disconnected when that happens) you get a socket error of ConnectionRefusedError.

My thoughts are this needs to handled by an except (either specific to ConnectionRefusedError or not) either in _joinThread (1525) or __init__ (738) to call the onConnectFail event. Unless there is a method recommended for fixing this in bot itself.

This could be considered medium as all it does is mean the person coding the bot has to be more advanced with their coding to check the bot joins a room etc. (ch.py just throws the exception, doesn't crash from what I can tell).

```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/bot/ch.py", line 1525, in _joinThread
    con = self._Room(room, mgr = self)
  File "/opt/bot/ch.py", line 738, in __init__
    if self._mgr: self._connect()
  File "/opt/bot/ch.py", line 746, in _connect
    self._sock.connect((self._server, self._port))
ConnectionRefusedError: [Errno 111] Connection refused
```

**Comment by asl97** [comment]
@james-d-elliott 
```
  def _joinThread(self):
    while True:
      room = self._rooms_queue.get()
      with self._rooms_lock:
        while True:
          try:
            con = self._Room(room, mgr = self)
          except:
            #self.onConnectFail(room)
            pass
          else:
            self._rooms[room] = con
            break
```
ugly and probably horrible.  the whole jointhread is just an horrible idea.

**Comment by asl97** [comment]
I changed it to use `socket.connect_ex`, it should just connect just fine and if something fails, the socket.recv should return an empty blank byte `b''` which will result in the regular `onDisconnect()` call

If an `onConnectFail()` is desired, I guess I could add a check somewhere, although it is currently being used for `denied` which I assume is for `banned`/`block` from chatango as a whole?

Not sure how `onConnectFail()` is being used and `onDisconnect` seem fitting so I will just leave it as it is for now

https://github.com/nhammond129/ch.py/commit/a936139fb0e9f2cde6334f71067cb1ca2c543c6d#diff-6325399cfe81734c1096a22792b0c2884856f4ed1f0f49927d5f7182e5667675R778

https://github.com/nhammond129/ch.py/blob/a936139fb0e9f2cde6334f71067cb1ca2c543c6d/ch.py#L774-L778

https://github.com/nhammond129/ch.py/blob/a936139fb0e9f2cde6334f71067cb1ca2c543c6d/ch.py#L2011-L2019

**Comment by asl97** [comment]
Just realized `onConnectFail()` is also called when trying to connect to a non existing room.

If `onConnectFail()` is being used to blacklist bad room names then it definitely shouldn't be used here to denote a connection failure.
