### ISSUE TITLE
Unicode support

### ISSUE THREAD

**Issue by JoeStaines** [nhammond129/ch.py#65]
I was messing around with stuff and noticed that it doesn't handle unicode all that well. I changed a couple of lines and managed to get it to receive and send characters outside of the ascii range, but i don't know if this would be enough or if there is another subtle reason why only ascii was being used.

Line changes:
Line 870
    self._process(food.decode("utf-8", errors="replace").rstrip("\r\n"))

Line 1442
    self._write(":".join(args).encode("utf-8") + terminator)

There is 2 other '_sendCommand' functions that only have encode(), so if this is acceptable then i imagine those would need to be changed. Any reason why unicode cant be support through this change?

**Comment by asl97** [comment]
windows & python2 iirc
https://github.com/Nullspeaker/ch.py/issues/2

**Comment by JoeStaines** [comment]
What is the problem with those exactly? I'm running Windows 7 and Python 2.7.8. Would using this fix break Py3 and linux stuff?

**Comment by asl97** [comment]
it break python2 and windows stuff

**Comment by asl97** [comment]
As far as I am aware of, we are now decoding without specifying the codec and it default to UTF-8 on python 3

https://docs.python.org/3/library/stdtypes.html#bytes.decode

Assuming not a issue anymore since python2 is discontinued
