### ISSUE TITLE
Anon pm no longer works

### ISSUE THREAD

**Issue by asl97** [nhammond129/ch.py#71]
The anon server seem to be gone.

Unable to connect to b1.chatango.com port 5222 anymore.

**Comment by donboricua** [comment]
I feel it was not necessary to make the `ANON_PM` class in the first place. But that's only my opinion.

**Comment by asl97** [comment]
@donboricua so you rather have anon pm lumped together with the PM class?

iirc, anon pm works differently from user pm,  trying to hack it into the PM class would be a mess.

I admit that the ANON_PM class could be implemented better, it should have just been a class which manage the pm objects, there are some stuff that should have been put inside ANON_PM_OBJECT.

**Comment by asl97** [comment]
in any case, that isn't really the issue.

the issue is the fact that the server doesn't seem to exist anymore.

**Comment by Uzytkownik2** [comment]
@asl97 anons can't send private messages so what is that topic about?

**Comment by asl97** [comment]
@Uzytkownik2 anon can send pm a few years ago,  they can't now.

**Comment by donboricua** [comment]
No, no. Just no need to have anon PM's period. As for the server: too many users block anon PM's so it was pretty much useless. Again my opinion for the need of it.

**Comment by asl97** [comment]
Anon PM was an useful features.

It doesn't matter if users block anon PM, just look at it another way if you must.
They just wouldn't be able to use the bot that use anon PM.
____
The current issue is that anon PM doesn't work anymore cause the backend for them disappear.
This issue isn't about whether it was useful/needed or not.

**Comment by piks** [comment]
I'm late to the party but,  chatango has slowly been removing anon things such as the anon pm,  i was surprized it lasted as long as it did since they removed the clients ability to pm as anon at least a year and a half ago

**Comment by Skarlett** [comment]
Look at the _getAuth function, a little modification you can get it to register an account.

**Comment by asl97** [comment]
@Skarlett the whole point of the anon pm is not needing an account.

**Comment by asl97** [comment]
___
@piks tbh, I don't know when the anon pm died

I just recently realize it after trying to figure out a few of the pm protocol args, which I am guessing, has something to do with anon pm.

**Comment by asl97** [comment]
I assume anon pm is still gone, this issue is so old, nothing we can really do to add anon pm, time to close this and move on I guess.

~~Unless we want to include some kind of dumb function built into the library to check though the connected room and if the user is found, send a message anonymously in the room~~
