### ISSUE TITLE
No more Python 2

### ISSUE THREAD

**Issue by TheClonerx** [nhammond129/ch.py#75]
This library has been Python 2 compatible for eons, it would be a good to clarify (in the README changelog) that Python 2 is no longer supported for good.

**Comment by asl97** [comment]
oh hey, someone actually still watches this repo,  this is just mostly me cleaning up my big fat mess that I left (joinThread)

I am sure I uses plenty of python3 only features, if anyone tries to use python 2, it will surely errors, it's been EoL for 3 years already anyway
